apiVersion: v1
kind: ConfigMap
metadata:
  name: expenselog-config
  namespace: expenselog
data:
  EXPENSE_CATEGORIES: "Food,Groceries,Travel,Rent,Utilities,Money Transfer,Entertainment,Healthcare,Shopping,Other"
  CURRENCY: ars

